name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'   # Runs daily at midnight UTC
  workflow_dispatch:       # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run User Statistician
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/userstats.svg
          include-title: true
          colors: light
          show-border: true
          commit-and-push: true
          commit-message: Automated update of GitHub stats
          fail-on-error: true
          locale: en
          border-radius: 6
          small-title: false
          max-languages: auto
          category-order: general, repositories, contributions, languages
          animated-language-chart: false
          language-animation-speed: 10
          image-width: 0
          top-icon: default
